# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9b2975c1f99910bf33a85e1ccb4fe5e7d19c619d6cebc37b2b594a8c4de8874a38a988d48e0de92f2cac6f087c669c3cb3b70e8a961aaaa4fab7b4f1d7c292c

test:
  secret_key_base: 4a90fbcef2bc4223e7fa023804f76ae04d42fa1a5443bf6d7c3412f3fd4ee3831523e5a85671e9d56e141536bee5723ed7a08ddeb64a6192e54f1957dc78f6cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
